# research_task:
#   description: >
#     Conduct a thorough research about {topic}z
#     Make sure you find any interesting and relevant information given
#     the current year is 2024.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledge reports with the mains topics, each with a full section of information.
#     Formated as markdown with out '```'

research_task:
  description: >
    Conduct a thorough research about {topic}.
    Only consider information after {fromdate} abd before {todate}.
    Make sure you find any interesting and relevant information given between {fromdate} and {todate}.
    Include all references.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic} with references.
    for thed time period of {fromdate} to {todate}.

reporting_task:
  description: >
    Review the context you received and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    Make sure it has references.
  expected_output: >
    A full report with the main topics, each with a full section of information.
    Formated as markdown. Put a main title on this report that say '{topic}: {fromdate}-{todate}'.
    Put a subtitle that says "Research".
    Add references to the bottom of the report.